export type CurrencyCode = "USD";

export type Product = {
  id: string;
  name: string;
  price: number;
  currency: CurrencyCode;
  imageUrl: string;
  sizes: readonly string[];
  colors: readonly string[];
  description: string;
  inStock: boolean;
  rating: number;
  tag: string;
};

export type CategoryKey = "shirts" | "tshirts" | "hoodies" | "pants";

export const productsByCategory: Record<CategoryKey, readonly Product[]> = {
  shirts: [
    {
      id: "shirt-001",
      name: "Classic Oxford Shirt",
      price: 49.99,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["white", "light-blue"],
      description: "A classic oxford shirt suitable for both casual and formal occasions.",
      inStock: true,
      rating: 4.6,
      tag: "new",
    },
    {
      id: "shirt-002",
      name: "Slim Fit Dress Shirt",
      price: 59.99,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L"],
      colors: ["black", "navy"],
      description: "Slim fit dress shirt with stretch fabric for all-day comfort.",
      inStock: true,
      rating: 4.3,
      tag: "bestseller",
    },
    {
      id: "shirt-003",
      name: "Linen Button-Down Shirt",
      price: 54.5,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["M", "L", "XL"],
      colors: ["sand", "white"],
      description: "Lightweight linen shirt, ideal for warmer weather.",
      inStock: true,
      rating: 4.4,
      tag: "summer",
    },
    {
      id: "shirt-004",
      name: "Checked Casual Shirt",
      price: 44.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["red-navy", "green-navy"],
      description: "Casual checked shirt with a relaxed fit.",
      inStock: true,
      rating: 4.1,
      tag: "casual",
    },
    {
      id: "shirt-005",
      name: "Stretch Poplin Shirt",
      price: 52.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["XS", "S", "M", "L"],
      colors: ["white", "light-grey"],
      description: "Poplin shirt with added stretch for flexibility.",
      inStock: false,
      rating: 4.0,
      tag: "limited",
    },
    {
      id: "shirt-006",
      name: "Denim Shirt",
      price: 57.99,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["mid-wash", "dark-wash"],
      description: "Durable denim shirt with snap buttons.",
      inStock: true,
      rating: 4.5,
      tag: "bestseller",
    },
    {
      id: "shirt-007",
      name: "Flannel Shirt",
      price: 48.5,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["M", "L", "XL"],
      colors: ["red-black", "blue-green"],
      description: "Soft brushed flannel for colder days.",
      inStock: true,
      rating: 4.7,
      tag: "winter",
    },
    {
      id: "shirt-008",
      name: "Short Sleeve Resort Shirt",
      price: 42.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L"],
      colors: ["tropical-print", "palms-print"],
      description: "Relaxed resort shirt with bold prints.",
      inStock: true,
      rating: 4.2,
      tag: "summer",
    },
    {
      id: "shirt-009",
      name: "Mandarin Collar Shirt",
      price: 46.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["white", "olive"],
      description: "Minimalist mandarin collar for a modern look.",
      inStock: false,
      rating: 4.1,
      tag: "trending",
    },
    {
      id: "shirt-010",
      name: "Textured Weave Shirt",
      price: 51.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["M", "L"],
      colors: ["stone", "navy"],
      description: "Subtle textured weave adds visual interest.",
      inStock: true,
      rating: 4.3,
      tag: "premium",
    },
    {
      id: "shirt-011",
      name: "Wrinkle-Free Shirt",
      price: 58.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["white", "blue-stripe"],
      description: "Easy-care shirt that stays smooth all day.",
      inStock: true,
      rating: 4.6,
      tag: "workwear",
    },
    {
      id: "shirt-012",
      name: "Micro-Check Dress Shirt",
      price: 55.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L"],
      colors: ["grey-check"],
      description: "Micro-check pattern suitable for office wear.",
      inStock: true,
      rating: 4.2,
      tag: "office",
    },
    {
      id: "shirt-013",
      name: "Corduroy Shirt",
      price: 63.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["M", "L", "XL"],
      colors: ["tan", "forest"],
      description: "Thick corduroy shirt that can double as a light jacket.",
      inStock: true,
      rating: 4.4,
      tag: "fall",
    },
    {
      id: "shirt-014",
      name: "Chambray Shirt",
      price: 47.5,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["light-denim"],
      description: "Soft chambray fabric for a relaxed look.",
      inStock: true,
      rating: 4.3,
      tag: "casual",
    },
    {
      id: "shirt-015",
      name: "Printed Short Sleeve Shirt",
      price: 39.99,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L"],
      colors: ["navy-print", "white-print"],
      description: "Printed short sleeve shirt with a slim cut.",
      inStock: false,
      rating: 3.9,
      tag: "sale",
    },
    {
      id: "shirt-016",
      name: "Stretch Formal Shirt",
      price: 62.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["white", "sky-blue"],
      description: "Formal shirt with stretch and a tailored fit.",
      inStock: true,
      rating: 4.7,
      tag: "premium",
    },
    {
      id: "shirt-017",
      name: "Oversized Utility Shirt",
      price: 53.5,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["M", "L", "XL"],
      colors: ["khaki", "charcoal"],
      description: "Utility-inspired shirt with large chest pockets.",
      inStock: true,
      rating: 4.2,
      tag: "streetwear",
    },
    {
      id: "shirt-018",
      name: "Seersucker Stripe Shirt",
      price: 49.5,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L"],
      colors: ["blue-stripe"],
      description: "Breathable seersucker fabric with classic stripes.",
      inStock: true,
      rating: 4.4,
      tag: "summer",
    },
    {
      id: "shirt-019",
      name: "Grandad Collar Shirt",
      price: 45.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["white", "ink-blue"],
      description: "Collarless shirt with a clean, modern feel.",
      inStock: false,
      rating: 4.0,
      tag: "trending",
    },
    {
      id: "shirt-020",
      name: "Heavyweight Work Shirt",
      price: 64.5,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["M", "L", "XL", "XXL"],
      colors: ["coal", "army"],
      description: "Rugged heavyweight shirt built for durability.",
      inStock: true,
      rating: 4.6,
      tag: "workwear",
    },
  ],
  tshirts: [
    {
      id: "tshirt-001",
      name: "Basic Crewneck T-Shirt",
      price: 19.99,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["white", "black", "grey"],
      description: "Soft cotton crewneck tee for everyday wear.",
      inStock: true,
      rating: 4.8,
      tag: "bestseller",
    },
    {
      id: "tshirt-002",
      name: "Graphic Print T-Shirt",
      price: 24.99,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["charcoal"],
      description: "Modern graphic tee with a relaxed fit.",
      inStock: false,
      rating: 4.2,
      tag: "limited",
    },
    {
      id: "tshirt-003",
      name: "V-Neck Essential Tee",
      price: 18.5,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["XS", "S", "M", "L"],
      colors: ["white", "navy"],
      description: "Lightweight v-neck tee that layers easily.",
      inStock: true,
      rating: 4.4,
      tag: "essentials",
    },
    {
      id: "tshirt-004",
      name: "Boxy Fit Street Tee",
      price: 27.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["black", "washed-grey"],
      description: "Boxy silhouette with dropped shoulders.",
      inStock: true,
      rating: 4.5,
      tag: "streetwear",
    },
    {
      id: "tshirt-005",
      name: "Pocket T-Shirt",
      price: 21.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L"],
      colors: ["olive", "brick"],
      description: "Everyday tee with a handy chest pocket.",
      inStock: true,
      rating: 4.3,
      tag: "casual",
    },
    {
      id: "tshirt-006",
      name: "Striped Retro Tee",
      price: 23.5,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["navy-stripe", "sunset-stripe"],
      description: "Retro striped tee with a soft hand feel.",
      inStock: true,
      rating: 4.6,
      tag: "retro",
    },
    {
      id: "tshirt-007",
      name: "Oversized Logo Tee",
      price: 29.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["M", "L", "XL"],
      colors: ["white", "black"],
      description: "Bold front logo on an oversized fit.",
      inStock: false,
      rating: 4.1,
      tag: "trending",
    },
    {
      id: "tshirt-008",
      name: "Longline Curved Hem Tee",
      price: 26.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L"],
      colors: ["charcoal", "sand"],
      description: "Extended length tee with curved hem.",
      inStock: true,
      rating: 4.2,
      tag: "streetwear",
    },
    {
      id: "tshirt-009",
      name: "Athletic Performance Tee",
      price: 32.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["electric-blue", "graphite"],
      description: "Moisture-wicking tee for training days.",
      inStock: true,
      rating: 4.7,
      tag: "active",
    },
    {
      id: "tshirt-010",
      name: "Organic Cotton Tee",
      price: 25.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["natural", "sage"],
      description: "Eco-friendly tee made from organic cotton.",
      inStock: true,
      rating: 4.8,
      tag: "sustainable",
    },
    {
      id: "tshirt-011",
      name: "Ringer Tee",
      price: 22.5,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L"],
      colors: ["white-navy", "white-red"],
      description: "Vintage-inspired ringer details on collar and sleeves.",
      inStock: true,
      rating: 4.3,
      tag: "retro",
    },
    {
      id: "tshirt-012",
      name: "Tie-Dye T-Shirt",
      price: 28.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["pastel-splash", "sunset-splash"],
      description: "Unique tie-dye patterns, no two tees are the same.",
      inStock: false,
      rating: 4.2,
      tag: "limited",
    },
    {
      id: "tshirt-013",
      name: "Henley T-Shirt",
      price: 24.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["heather-grey", "navy"],
      description: "Short-sleeve henley with a 3-button placket.",
      inStock: true,
      rating: 4.5,
      tag: "casual",
    },
    {
      id: "tshirt-014",
      name: "Slub Cotton Tee",
      price: 21.5,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["XS", "S", "M", "L"],
      colors: ["oatmeal", "ink"],
      description: "Textured slub cotton for a lived-in look.",
      inStock: true,
      rating: 4.1,
      tag: "essentials",
    },
    {
      id: "tshirt-015",
      name: "Minimal Embroidered Tee",
      price: 26.5,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L"],
      colors: ["black", "white"],
      description: "Small chest embroidery for a subtle statement.",
      inStock: true,
      rating: 4.4,
      tag: "trending",
    },
    {
      id: "tshirt-016",
      name: "Crop Fit Tee",
      price: 23.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["XS", "S", "M"],
      colors: ["white", "mauve"],
      description: "Cropped length tee with a boxy fit.",
      inStock: false,
      rating: 4.0,
      tag: "summer",
    },
    {
      id: "tshirt-017",
      name: "Muscle Fit Tee",
      price: 24.5,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["black", "olive"],
      description: "Body-hugging tee that highlights the shoulders and arms.",
      inStock: true,
      rating: 4.6,
      tag: "active",
    },
    {
      id: "tshirt-018",
      name: "All-Over Print Tee",
      price: 29.5,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L"],
      colors: ["geo-print", "abstract-print"],
      description: "All-over printed tee for a bold look.",
      inStock: true,
      rating: 4.2,
      tag: "statement",
    },
    {
      id: "tshirt-019",
      name: "Thermal Waffle Tee",
      price: 30.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["M", "L", "XL"],
      colors: ["charcoal", "taupe"],
      description: "Waffle-knit tee for cooler days.",
      inStock: true,
      rating: 4.5,
      tag: "fall",
    },
    {
      id: "tshirt-020",
      name: "Colorblock Panel Tee",
      price: 27.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["navy-white", "grey-black"],
      description: "Colorblock panels create a sporty vibe.",
      inStock: true,
      rating: 4.3,
      tag: "sporty",
    },
  ],
  hoodies: [
    {
      id: "hoodie-001",
      name: "Fleece Pullover Hoodie",
      price: 59.0,
      currency: "USD",
      imageUrl: "/images/products/hoodies/hoodie.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["heather-grey", "navy"],
      description: "Cozy fleece hoodie with kangaroo pocket.",
      inStock: true,
      rating: 4.7,
      tag: "new",
    },
    {
      id: "hoodie-002",
      name: "Zip-Up Hoodie",
      price: 64.0,
      currency: "USD",
      imageUrl: "/images/products/hoodies/hoodie.png",
      sizes: ["M", "L", "XL"],
      colors: ["black", "olive"],
      description: "Mid-weight zip hoodie, perfect for layering.",
      inStock: true,
      rating: 4.4,
      tag: "bestseller",
    },
    {
      id: "hoodie-003",
      name: "Oversized Street Hoodie",
      price: 69.0,
      currency: "USD",
      imageUrl: "/images/products/hoodies/hoodie.png",
      sizes: ["M", "L", "XL"],
      colors: ["washed-black", "stone"],
      description: "Oversized fit with dropped shoulders for a streetwear look.",
      inStock: true,
      rating: 4.6,
      tag: "streetwear",
    },
    {
      id: "hoodie-004",
      name: "Logo Graphic Hoodie",
      price: 72.0,
      currency: "USD",
      imageUrl: "/images/products/hoodies/hoodie.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["black", "white"],
      description: "Bold front logo graphic on a soft fleece base.",
      inStock: false,
      rating: 4.3,
      tag: "trending",
    },
    {
      id: "hoodie-005",
      name: "Performance Training Hoodie",
      price: 79.0,
      currency: "USD",
      imageUrl: "/images/products/hoodies/hoodie.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["graphite", "electric-blue"],
      description: "Moisture-wicking performance fabric for workouts.",
      inStock: true,
      rating: 4.8,
      tag: "active",
    },
    {
      id: "hoodie-006",
      name: "Sherpa Lined Hoodie",
      price: 84.0,
      currency: "USD",
      imageUrl: "/images/products/hoodies/hoodie.png",
      sizes: ["M", "L", "XL", "XXL"],
      colors: ["navy", "forest"],
      description: "Ultra-warm sherpa lining for extra insulation.",
      inStock: true,
      rating: 4.7,
      tag: "winter",
    },
    {
      id: "hoodie-007",
      name: "Cropped Hoodie",
      price: 62.0,
      currency: "USD",
      imageUrl: "/images/products/hoodies/hoodie.png",
      sizes: ["XS", "S", "M"],
      colors: ["mauve", "cream"],
      description: "Cropped length hoodie with ribbed hem and cuffs.",
      inStock: true,
      rating: 4.4,
      tag: "trending",
    },
    {
      id: "hoodie-008",
      name: "Colorblock Hoodie",
      price: 68.0,
      currency: "USD",
      imageUrl: "/images/products/hoodies/hoodie.png",
      sizes: ["S", "M", "L"],
      colors: ["navy-white-red", "grey-black"],
      description: "Colorblock design for a sporty look.",
      inStock: false,
      rating: 4.2,
      tag: "sporty",
    },
    {
      id: "hoodie-009",
      name: "Minimal Zip Hoodie",
      price: 66.0,
      currency: "USD",
      imageUrl: "/images/products/hoodies/hoodie.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["black", "charcoal"],
      description: "Clean, minimal design with concealed zipper.",
      inStock: true,
      rating: 4.5,
      tag: "essentials",
    },
    {
      id: "hoodie-010",
      name: "Organic Cotton Hoodie",
      price: 78.0,
      currency: "USD",
      imageUrl: "/images/products/hoodies/hoodie.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["natural", "sage"],
      description: "Made from certified organic cotton fleece.",
      inStock: true,
      rating: 4.8,
      tag: "sustainable",
    },
    {
      id: "hoodie-011",
      name: "Tie-Dye Hoodie",
      price: 74.0,
      currency: "USD",
      imageUrl: "/images/products/hoodies/hoodie.png",
      sizes: ["S", "M", "L"],
      colors: ["pastel-splash", "midnight-splash"],
      description: "Hand-dyed hoodie with unique patterns.",
      inStock: true,
      rating: 4.3,
      tag: "limited",
    },
    {
      id: "hoodie-012",
      name: "Tech Fleece Hoodie",
      price: 89.0,
      currency: "USD",
      imageUrl: "/images/products/hoodies/hoodie.png",
      sizes: ["M", "L", "XL"],
      colors: ["black", "storm-grey"],
      description: "Lightweight tech fleece with bonded zippers.",
      inStock: true,
      rating: 4.7,
      tag: "premium",
    },
    {
      id: "hoodie-013",
      name: "Half-Zip Hoodie",
      price: 71.0,
      currency: "USD",
      imageUrl: "/images/products/hoodies/hoodie.png",
      sizes: ["S", "M", "L"],
      colors: ["sky-blue", "charcoal"],
      description: "Half-zip neckline for customizable ventilation.",
      inStock: false,
      rating: 4.2,
      tag: "casual",
    },
    {
      id: "hoodie-014",
      name: "Heavyweight Work Hoodie",
      price: 82.0,
      currency: "USD",
      imageUrl: "/images/products/hoodies/hoodie.png",
      sizes: ["M", "L", "XL", "XXL"],
      colors: ["coal", "brown"],
      description: "Durable heavyweight hoodie built for work sites.",
      inStock: true,
      rating: 4.6,
      tag: "workwear",
    },
    {
      id: "hoodie-015",
      name: "Camo Print Hoodie",
      price: 70.0,
      currency: "USD",
      imageUrl: "/images/products/hoodies/hoodie.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["forest-camo", "urban-camo"],
      description: "All-over camo print on brushed fleece.",
      inStock: true,
      rating: 4.4,
      tag: "streetwear",
    },
    {
      id: "hoodie-016",
      name: "Quarter-Zip Funnel Hoodie",
      price: 76.0,
      currency: "USD",
      imageUrl: "/images/products/hoodies/hoodie.png",
      sizes: ["S", "M", "L"],
      colors: ["oatmeal", "ink"],
      description: "Funnel neck quarter-zip hoodie for extra warmth.",
      inStock: true,
      rating: 4.5,
      tag: "fall",
    },
    {
      id: "hoodie-017",
      name: "Cropped Zip Hoodie",
      price: 64.0,
      currency: "USD",
      imageUrl: "/images/products/hoodies/hoodie.png",
      sizes: ["XS", "S", "M"],
      colors: ["lilac", "white"],
      description: "Cropped hoodie with full zip and drawstring hem.",
      inStock: false,
      rating: 4.1,
      tag: "trending",
    },
    {
      id: "hoodie-018",
      name: "Ribbed Hem Hoodie",
      price: 67.0,
      currency: "USD",
      imageUrl: "/images/products/hoodies/hoodie.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["heather-oat", "navy"],
      description: "Ribbed hem and cuffs for a snug fit.",
      inStock: true,
      rating: 4.3,
      tag: "essentials",
    },
    {
      id: "hoodie-019",
      name: "Windbreaker Hoodie",
      price: 88.0,
      currency: "USD",
      imageUrl: "/images/products/hoodies/hoodie.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["black", "olive"],
      description: "Lightweight wind-resistant shell with hoodie styling.",
      inStock: true,
      rating: 4.4,
      tag: "outdoor",
    },
    {
      id: "hoodie-020",
      name: "Embroidered Logo Hoodie",
      price: 73.0,
      currency: "USD",
      imageUrl: "/images/products/hoodies/hoodie.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["burgundy", "navy"],
      description: "Subtle embroidered logo on chest.",
      inStock: true,
      rating: 4.6,
      tag: "premium",
    },
  ],
  pants: [
    {
      id: "pants-001",
      name: "Slim Fit Chinos",
      price: 69.99,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["30", "32", "34", "36"],
      colors: ["khaki", "navy"],
      description: "Versatile slim fit chinos for work or weekend.",
      inStock: true,
      rating: 4.5,
      tag: "bestseller",
    },
    {
      id: "pants-002",
      name: "Jogger Sweatpants",
      price: 49.99,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["black", "charcoal"],
      description: "Comfortable joggers with elastic cuffs and drawstring waist.",
      inStock: true,
      rating: 4.6,
      tag: "new",
    },
    {
      id: "pants-003",
      name: "Tapered Dress Pants",
      price: 79.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["30", "32", "34", "36", "38"],
      colors: ["black", "charcoal"],
      description: "Tailored dress pants with a modern tapered leg.",
      inStock: true,
      rating: 4.4,
      tag: "office",
    },
    {
      id: "pants-004",
      name: "Relaxed Fit Chinos",
      price: 64.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["32", "34", "36", "38"],
      colors: ["stone", "olive"],
      description: "Relaxed through the thigh with a straight leg opening.",
      inStock: true,
      rating: 4.2,
      tag: "casual",
    },
    {
      id: "pants-005",
      name: "Cargo Pants",
      price: 72.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["30", "32", "34", "36"],
      colors: ["coyote", "army"],
      description: "Multiple cargo pockets with adjustable hem tabs.",
      inStock: true,
      rating: 4.5,
      tag: "utility",
    },
    {
      id: "pants-006",
      name: "Slim Fit Jeans",
      price: 74.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["28", "30", "32", "34", "36"],
      colors: ["dark-wash", "mid-wash"],
      description: "Classic 5-pocket slim jeans with a bit of stretch.",
      inStock: true,
      rating: 4.6,
      tag: "denim",
    },
    {
      id: "pants-007",
      name: "Straight Fit Jeans",
      price: 72.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["30", "32", "34", "36", "38"],
      colors: ["light-wash", "indigo"],
      description: "Straight leg jeans with a relaxed thigh.",
      inStock: false,
      rating: 4.3,
      tag: "denim",
    },
    {
      id: "pants-008",
      name: "Athletic Taper Pants",
      price: 76.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["30", "32", "34", "36"],
      colors: ["black", "charcoal"],
      description: "Room in the seat and thigh with a tapered leg.",
      inStock: true,
      rating: 4.5,
      tag: "workwear",
    },
    {
      id: "pants-009",
      name: "Tech Track Pants",
      price: 69.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["black", "graphite"],
      description: "Lightweight track pants with zip hems.",
      inStock: true,
      rating: 4.7,
      tag: "active",
    },
    {
      id: "pants-010",
      name: "Linen Drawstring Pants",
      price: 66.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["sand", "natural"],
      description: "Breathable linen blend with relaxed fit and drawstring waist.",
      inStock: true,
      rating: 4.4,
      tag: "summer",
    },
    {
      id: "pants-011",
      name: "Tailored Wool Trousers",
      price: 98.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["30", "32", "34", "36"],
      colors: ["charcoal", "navy"],
      description: "Premium wool trousers with sharp tailoring.",
      inStock: true,
      rating: 4.8,
      tag: "premium",
    },
    {
      id: "pants-012",
      name: "Corduroy Pants",
      price: 71.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["30", "32", "34", "36", "38"],
      colors: ["tan", "forest"],
      description: "Fine-wale corduroy with a straight leg.",
      inStock: true,
      rating: 4.5,
      tag: "fall",
    },
    {
      id: "pants-013",
      name: "Wide Leg Trousers",
      price: 74.5,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L"],
      colors: ["black", "stone"],
      description: "Flowy wide leg for a relaxed yet polished silhouette.",
      inStock: false,
      rating: 4.2,
      tag: "trending",
    },
    {
      id: "pants-014",
      name: "Cropped Ankle Pants",
      price: 68.5,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["28", "30", "32", "34"],
      colors: ["navy", "ash"],
      description: "Cropped just above the ankle with a slim leg.",
      inStock: true,
      rating: 4.3,
      tag: "modern",
    },
    {
      id: "pants-015",
      name: "Pleated Trousers",
      price: 79.5,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["30", "32", "34", "36"],
      colors: ["grey", "ink"],
      description: "Front pleats and relaxed fit through the thigh.",
      inStock: true,
      rating: 4.4,
      tag: "office",
    },
    {
      id: "pants-016",
      name: "Flannel Lounge Pants",
      price: 52.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["S", "M", "L", "XL"],
      colors: ["plaid-navy", "plaid-red"],
      description: "Brushed flannel lounge pants with drawstring waist.",
      inStock: true,
      rating: 4.6,
      tag: "loungewear",
    },
    {
      id: "pants-017",
      name: "Slim Fit Suit Pants",
      price: 92.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["30", "32", "34", "36"],
      colors: ["midnight", "charcoal"],
      description: "Suit pants with a sharp slim profile.",
      inStock: true,
      rating: 4.7,
      tag: "formal",
    },
    {
      id: "pants-018",
      name: "High-Rise Trousers",
      price: 77.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["24", "26", "28", "30"],
      colors: ["black", "camel"],
      description: "High-rise waist with a straight tailored leg.",
      inStock: false,
      rating: 4.3,
      tag: "trending",
    },
    {
      id: "pants-019",
      name: "Stretch Travel Pants",
      price: 83.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["30", "32", "34", "36"],
      colors: ["charcoal", "navy"],
      description: "Wrinkle-resistant stretch fabric ideal for travel.",
      inStock: true,
      rating: 4.8,
      tag: "travel",
    },
    {
      id: "pants-020",
      name: "Utility Carpenter Pants",
      price: 73.0,
      currency: "USD",
      imageUrl: "/clothing-outline.png",
      sizes: ["30", "32", "34", "36", "38"],
      colors: ["sand", "coal"],
      description: "Workwear-inspired carpenter pants with tool loops.",
      inStock: true,
      rating: 4.5,
      tag: "workwear",
    },
  ],
};
